const sports = {
  nfl: {
    label: 'NFL',
    total: 32,
    conferences: ['AFC', 'NFC'],
    divsPerConf: 4,
    teams: {
      buf:  { name: 'Bills',       bg: '#00338D', fg: '#C60C30' },
      mia:  { name: 'Dolphins',    bg: '#008E97', fg: '#fff' },
      ne:   { name: 'Patriots',    bg: '#002244', fg: '#C60C30' },
      nyj:  { name: 'Jets',        bg: '#125740', fg: '#fff' },
      bal:  { name: 'Ravens',      bg: '#241773', fg: '#9E7C0C' },
      cin:  { name: 'Bengals',     bg: '#FB4F14', fg: '#000' },
      cle:  { name: 'Browns',      bg: '#311D00', fg: '#FF3C00' },
      pit:  { name: 'Steelers',    bg: '#101820', fg: '#FFB612' },
      hou:  { name: 'Texans',      bg: '#03202F', fg: '#A71930' },
      ind:  { name: 'Colts',       bg: '#002C5F', fg: '#A2AAAD' },
      jax:  { name: 'Jaguars',     bg: '#101820', fg: '#9F792C' },
      ten:  { name: 'Titans',      bg: '#0C2340', fg: '#4B92DB' },
      den:  { name: 'Broncos',     bg: '#FB4F14', fg: '#002244' },
      kc:   { name: 'Chiefs',      bg: '#E31837', fg: '#FFB81C' },
      lv:   { name: 'Raiders',     bg: '#2B2B2B', fg: '#A5ACAF' },
      lac:  { name: 'Chargers',    bg: '#0080C6', fg: '#FFC20E' },
      dal:  { name: 'Cowboys',     bg: '#003594', fg: '#869397' },
      nyg:  { name: 'Giants',      bg: '#0B2265', fg: '#A71930' },
      phi:  { name: 'Eagles',      bg: '#004C54', fg: '#A5ACAF' },
      was:  { name: 'Commanders',  bg: '#5A1414', fg: '#FFB612' },
      chi:  { name: 'Bears',       bg: '#0B162A', fg: '#C83803' },
      det:  { name: 'Lions',       bg: '#0076B6', fg: '#B0B7BC' },
      gb:   { name: 'Packers',     bg: '#203731', fg: '#FFB612' },
      min:  { name: 'Vikings',     bg: '#4F2683', fg: '#FFC62F' },
      atl:  { name: 'Falcons',     bg: '#A71930', fg: '#fff' },
      car:  { name: 'Panthers',    bg: '#0085CA', fg: '#101820' },
      no:   { name: 'Saints',      bg: '#101820', fg: '#D3BC8D' },
      tb:   { name: 'Buccaneers',  bg: '#D50A0A', fg: '#FF7900' },
      ari:  { name: 'Cardinals',   bg: '#97233F', fg: '#FFB612' },
      lar:  { name: 'Rams',        bg: '#003594', fg: '#FFA300' },
      sf:   { name: '49ers',       bg: '#AA0000', fg: '#B3995D' },
      sea:  { name: 'Seahawks',    bg: '#002244', fg: '#69BE28' },
    },
    divisions: [
      { label: 'AFC East',  ids: ['buf','mia','ne','nyj'] },
      { label: 'AFC North', ids: ['bal','cin','cle','pit'] },
      { label: 'AFC South', ids: ['hou','ind','jax','ten'] },
      { label: 'AFC West',  ids: ['den','kc','lv','lac'] },
      { label: 'NFC East',  ids: ['dal','nyg','phi','was'] },
      { label: 'NFC North', ids: ['chi','det','gb','min'] },
      { label: 'NFC South', ids: ['atl','car','no','tb'] },
      { label: 'NFC West',  ids: ['ari','lar','sf','sea'] },
    ],
  },
  mlb: {
    label: 'MLB',
    total: 30,
    conferences: ['AL', 'NL'],
    divsPerConf: 3,
    teams: {
      bal:  { name: 'Orioles',     bg: '#DF4601', fg: '#000' },
      bos:  { name: 'Red Sox',     bg: '#BD3039', fg: '#fff' },
      nyy:  { name: 'Yankees',     bg: '#003087', fg: '#fff' },
      tb:   { name: 'Rays',        bg: '#092C5C', fg: '#8FBCE6' },
      tor:  { name: 'Blue Jays',   bg: '#134A8E', fg: '#fff' },
      chw:  { name: 'White Sox',   bg: '#27251F', fg: '#C4CED4' },
      cle:  { name: 'Guardians',   bg: '#00385D', fg: '#E31937' },
      det:  { name: 'Tigers',      bg: '#0C2340', fg: '#FA4616' },
      kc:   { name: 'Royals',      bg: '#004687', fg: '#C09A5B' },
      min:  { name: 'Twins',       bg: '#002B5C', fg: '#D31145' },
      hou:  { name: 'Astros',      bg: '#002D62', fg: '#EB6E1F' },
      laa:  { name: 'Angels',      bg: '#BA0021', fg: '#fff' },
      oak:  { name: 'Athletics',   bg: '#003831', fg: '#EFB21E' },
      sea:  { name: 'Mariners',    bg: '#0C2C56', fg: '#C4CED4' },
      tex:  { name: 'Rangers',     bg: '#003278', fg: '#C0111F' },
      atl:  { name: 'Braves',      bg: '#CE1141', fg: '#13274F' },
      mia:  { name: 'Marlins',     bg: '#00A3E0', fg: '#101820' },
      nym:  { name: 'Mets',        bg: '#002D72', fg: '#FF5910' },
      phi:  { name: 'Phillies',    bg: '#E81828', fg: '#fff' },
      was:  { name: 'Nationals',   bg: '#AB0003', fg: '#fff' },
      chc:  { name: 'Cubs',        bg: '#0E3386', fg: '#CC3433' },
      cin:  { name: 'Reds',        bg: '#C6011F', fg: '#fff' },
      mil:  { name: 'Brewers',     bg: '#12284B', fg: '#FFC52F' },
      pit:  { name: 'Pirates',     bg: '#27251F', fg: '#FDB827' },
      stl:  { name: 'Cardinals',   bg: '#C41E3A', fg: '#fff' },
      ari:  { name: 'D-backs',     bg: '#A71930', fg: '#E3D4AD' },
      col:  { name: 'Rockies',     bg: '#33006F', fg: '#C4CED4' },
      lad:  { name: 'Dodgers',     bg: '#005A9C', fg: '#fff' },
      sd:   { name: 'Padres',      bg: '#2F241D', fg: '#FFC425' },
      sf:   { name: 'Giants',      bg: '#27251F', fg: '#FD5A1E' },
    },
    divisions: [
      { label: 'AL East',    ids: ['bal','bos','nyy','tb','tor'] },
      { label: 'AL Central', ids: ['chw','cle','det','kc','min'] },
      { label: 'AL West',    ids: ['hou','laa','oak','sea','tex'] },
      { label: 'NL East',    ids: ['atl','mia','nym','phi','was'] },
      { label: 'NL Central', ids: ['chc','cin','mil','pit','stl'] },
      { label: 'NL West',    ids: ['ari','col','lad','sd','sf'] },
    ],
  },
  nba: {
    label: 'NBA',
    total: 30,
    conferences: ['East', 'West'],
    divsPerConf: 3,
    teams: {
      bos:  { name: 'Celtics',       bg: '#007A33', fg: '#fff' },
      bkn:  { name: 'Nets',          bg: '#000000', fg: '#fff' },
      nyk:  { name: 'Knicks',        bg: '#F58426', fg: '#006BB6' },
      phi:  { name: '76ers',         bg: '#006BB6', fg: '#ED174C' },
      tor:  { name: 'Raptors',       bg: '#CE1141', fg: '#fff' },
      chi:  { name: 'Bulls',         bg: '#CE1141', fg: '#000' },
      cle:  { name: 'Cavaliers',     bg: '#860038', fg: '#FDBB30' },
      det:  { name: 'Pistons',       bg: '#C8102E', fg: '#1D42BA' },
      ind:  { name: 'Pacers',        bg: '#002D62', fg: '#FDBB30' },
      mil:  { name: 'Bucks',         bg: '#00471B', fg: '#EEE1C6' },
      atl:  { name: 'Hawks',         bg: '#C1D32F', fg: '#E03A3E' },
      cha:  { name: 'Hornets',       bg: '#1D1160', fg: '#00788C' },
      mia:  { name: 'Heat',          bg: '#98002E', fg: '#F9A01B' },
      orl:  { name: 'Magic',         bg: '#0077C0', fg: '#C4CED4' },
      was:  { name: 'Wizards',       bg: '#002B5C', fg: '#E31837' },
      den:  { name: 'Nuggets',       bg: '#0E2240', fg: '#FEC524' },
      min:  { name: 'Timberwolves',  bg: '#0C2340', fg: '#236192' },
      okc:  { name: 'Thunder',       bg: '#007AC1', fg: '#EF3B24' },
      por:  { name: 'Trail Blazers', bg: '#E03A3E', fg: '#000' },
      uta:  { name: 'Jazz',          bg: '#002B5C', fg: '#00471B' },
      gsw:  { name: 'Warriors',      bg: '#1D428A', fg: '#FFC72C' },
      lac:  { name: 'Clippers',      bg: '#C8102E', fg: '#1D428A' },
      lal:  { name: 'Lakers',        bg: '#552583', fg: '#FDB927' },
      phx:  { name: 'Suns',          bg: '#1D1160', fg: '#E56020' },
      sac:  { name: 'Kings',         bg: '#5A2D81', fg: '#63727A' },
      dal:  { name: 'Mavericks',     bg: '#00538C', fg: '#002B5E' },
      hou:  { name: 'Rockets',       bg: '#CE1141', fg: '#000' },
      mem:  { name: 'Grizzlies',     bg: '#5D76A9', fg: '#12173F' },
      nop:  { name: 'Pelicans',      bg: '#0C2340', fg: '#C8102E' },
      sas:  { name: 'Spurs',         bg: '#C4CED4', fg: '#000' },
    },
    divisions: [
      { label: 'East Atlantic',  ids: ['bos','bkn','nyk','phi','tor'] },
      { label: 'East Central',   ids: ['chi','cle','det','ind','mil'] },
      { label: 'East Southeast', ids: ['atl','cha','mia','orl','was'] },
      { label: 'West Northwest', ids: ['den','min','okc','por','uta'] },
      { label: 'West Pacific',   ids: ['gsw','lac','lal','phx','sac'] },
      { label: 'West Southwest', ids: ['dal','hou','mem','nop','sas'] },
    ],
  },
};
